/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IWineryNFTInterface extends utils.Interface {
  contractName: "IWineryNFT";
  functions: {
    "launchpadMint(address,uint256,uint256,bool)": FunctionFragment;
    "tokenUnfreeze(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "launchpadMint",
    values: [string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenUnfreeze",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "launchpadMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenUnfreeze",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IWineryNFT extends BaseContract {
  contractName: "IWineryNFT";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IWineryNFTInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    launchpadMint(
      to: string,
      level: BigNumberish,
      robiBoost: BigNumberish,
      freeze: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenUnfreeze(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  launchpadMint(
    to: string,
    level: BigNumberish,
    robiBoost: BigNumberish,
    freeze: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenUnfreeze(
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    launchpadMint(
      to: string,
      level: BigNumberish,
      robiBoost: BigNumberish,
      freeze: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenUnfreeze(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    launchpadMint(
      to: string,
      level: BigNumberish,
      robiBoost: BigNumberish,
      freeze: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenUnfreeze(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    launchpadMint(
      to: string,
      level: BigNumberish,
      robiBoost: BigNumberish,
      freeze: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenUnfreeze(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
